### ISSUE TITLE
Security scan: OWASP Mobile Top 10

### ISSUE THREAD

**Issue by rparet** [tripleblindmarket/private-kit#104]
We should scan the v1 release candidate to make sure we haven't introduced any obvious security problems. OWASP Mobile Top 10 is a good start.

**Comment by nimittjnl** [comment]
[PV 19 Mar 2020.pdf](https://github.com/tripleblindmarket/private-kit/files/4355555/PV.19.Mar.2020.pdf)
Security audit report for android build 19 Mar 2020.  Status: all green

**Comment by rparet** [comment]
Resolved.
