### ISSUE TITLE
Export File extension and format

### ISSUE THREAD

**Issue by nimittjnl** [tripleblindmarket/private-kit#105]
I would recommend that we have an appropriate extension in place of the current null
Field format can be key value pair OR csv OR JSON.  Decision is required.

**Comment by tushar-dadlani** [comment]
Is this the same or reltaed to ? #68  

For gps trajectories, GPX is a file format used by Open Street Map for sharing trajectories.

**Comment by tushar-dadlani** [comment]
This should be fixed by #174
