### ISSUE TITLE
Playstore Install and Install Experience

### ISSUE THREAD

**Issue by VivianGomes** [tripleblindmarket/private-kit#111]
Search for the app through the link and installation from Play-store isn't working effectively. For more people to use and contribute to the safe data share, locate>download>install>get started experience needs to be improved .

**Comment by rparet** [comment]
Hi there! Could you explain a little bit more about your experience? We're definitely looking to improve here. If you could attach some screenshots of what you're seeing and what you think should be improved, it would help us greatly. Thanks!
