### ISSUE TITLE
React Native CLI uses autolinking error, please help thankyou.

### ISSUE THREAD

**Issue by santoscarlo** [tripleblindmarket/private-kit#1167]

**Comment by johnschoeman** [comment]
@santoscarlo , sorry for the delay, not sure if anyone is actively responsible for github issues.  Is this still a problem for you?

**Comment by santoscarlo** [comment]
i fixed it bro few days ago, thankyou for your response. :)

**Comment by santoscarlo** [comment]
> this happen when i runnning yarn run-android-gps on my terminal, but i already setup the path environment variables
> $ react-native run-android --variant=btDebug --appId=org.pathcheck.covidsafepathsBt
> error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
> 
> * react-native-local-resource (to unlink run: "react-native unlink react-native-local-resource")
>   This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink " and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
>   Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
>   info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
