### ISSUE TITLE
iOS bottom bar covers buttons

### ISSUE THREAD

**Issue by amclough** [tripleblindmarket/private-kit#134]
![issue](https://user-images.githubusercontent.com/59571529/77217236-47a9d400-6af7-11ea-95cf-5b5967851a63.jpeg)

**Comment by thetimbanks** [comment]
@rparet What version of the hardware did you view this on? I viewed this screen on an iPhone 8 and iPhone 11 and I don't see this issue occuring.

**Comment by rparet** [comment]
No longer an issue.
