### ISSUE TITLE
Show software info / licenses

### ISSUE THREAD

**Issue by penrods** [tripleblindmarket/private-kit#135]
We need a way to show acknowledgement and the licenses for components.

UI thought:  From the main page just add a hamburger menu (three vertical dots) in the upper-right.  That will drop down a menu with "Open Source Licenses".  The menu item brings up a screen.  In that screen you will see something like this:

-------
 < **Open Source Licenses**

**Library Foo**
```
The library is licensed under blah blah

Yadda yadda yadda
```

**Library Bar**
```
The library is licensed under yadda yadda

Blah blah blah
```

**Comment by StartupSam** [comment]
Will get started on this tonight and get a PR up tomorrow.

I imagine we'll want a basic form of navigation in place for the various app functions that are coming (viewing own map, viewing public intersection points, etc) - might make sense to add a bottom tab navigator with placeholder screens for functions that aren't ready yet.
