### ISSUE TITLE
Fully-native version for Android?

### ISSUE THREAD

**Issue by dbrant** [tripleblindmarket/private-kit#145]
I've taken the liberty of throwing together a prototype of a fully native Android version of Private Kit (based on code I've had lying around for a while):
https://github.com/dbrant/privatekit

The rationale? From what I've seen in the past, React Native often fails to account for various OS-specific or even manufacturer-specific quirks, especially when dealing with finicky hardware functionality like location tracking in the background. Eventually you'd need an increasing number of hacks and patches (and chasing after obscure bugs), until they outweigh the effort it would have taken to build a truly native app from the get-go.

Let me know if a fully native version is something you'd like to pursue. I'll be happy to maintain it as a volunteer.

**Comment by rparet** [comment]
Thank you @dbrant! Right now, we're trying to maximize for rapid development and deployment so staying with a cross-platform framework is necessary at present. Totally hear you on the benefits of native though. If you want to keep maintaining your native fork as we go forward, we may be able to revisit it in the v3 timeframe.

Closing this.
