### ISSUE TITLE
Feature: In-app map display of trails

### ISSUE THREAD

**Issue by micksabox** [tripleblindmarket/private-kit#146]
Relying on the [safe places web app](https://github.com/tripleblindmarket/safe-places) introduces an additional dependency into the contact tracing experience.

It has been pointed in discussions that adoption of the app could be user-driven (bottom-up) instead of public-health or government driven (top-down). While I fully understand the need for a top-down approach, there is a pressing need for a contact tracing solution, and the bottom-up approach should be worked on in parallel.

The mobile app should have the ability to view the location data in-app, and also perform any redaction in-app. This will also reduce the risk of private data to be exposed, as everything will be in-app. Also, the user experience will be improved because there would be no need to also use the Safe Places web app.

**Comment by tremblerz** [comment]
Safe-places is for city officials who are not looking at the individual data all the time but only when a carrier gives them consent and provides the data.
Having said that, the ability to view their own trails for a user is a great suggestion! 
it is being done as part of this feature #131 
It will be getting pushed on the repository soon

**Comment by micksabox** [comment]
Ok, perhaps I misunderstood the Point of safe places then. I changed the name of in-app display of trails. The description and context in this issue could be re-used.

**Comment by rparet** [comment]
Hey there. Going to consolidate this feedback into #131 and close this as a dupe. Thanks!
