### ISSUE TITLE
Connection with 

### ISSUE THREAD

**Issue by Utzel-Butzel** [tripleblindmarket/private-kit#159]
Hi Private kit team, it looks like we are building a similar project and both our projects work in react-native. Do you plan adding a map and warning solution? In our approach your location history will be compared to an online database, so you don't have to share any of your private data.

https://github.com/wirewirewirewire/pandoa
The project is GNU/GPL, but we would be also totally fine with changing it to MIT.

**Comment by rparet** [comment]
Hey there. You can check out the roadmap on github (look at v2 and v3 milestone). If you'd like to join us, we'd love the help.

**Comment by rparet** [comment]
Closing, please join us on Slack if you'd like to collaborate!
