### ISSUE TITLE
Security audit report 24 Mar 2020

### ISSUE THREAD

**Issue by nimittjnl** [tripleblindmarket/private-kit#179]
Security audit report
![Screenshot 2020-03-24 at 6 46 53 PM](https://user-images.githubusercontent.com/62194377/77430035-8cd44b80-6e00-11ea-8276-22be7e7469ad.png)
[PV 24 Mar 2020.pdf](https://github.com/tripleblindmarket/private-kit/files/4375448/PV.24.Mar.2020.pdf)

**Comment by E3V3A** [comment]
maybe mark with version number instead?

**Comment by WriteCodeEveryday** [comment]
I think all of these are in the built-in libraries as this is a React Native app..
