### ISSUE TITLE
BUG: iOS version not building from 'develop'

### ISSUE THREAD

**Issue by penrods** [tripleblindmarket/private-kit#18]
Currently you cannot build the iOS version of the app.  The error reference the 'tripleblind' app, so it is likely that it has to do with renaming packages.

Can test against the first release off of the 'master' branch, which I believe did function.

**Comment by nic-rodriguez** [comment]
The most recent develop branch seems to build fine for me using a simulator for iPhone 11, still need to test locally to see if that responds differently

**Comment by penrods** [comment]
@vitorpamplona was having issues yesterday, so let's confirm (especially since he is doing the builds!)

**Comment by penrods** [comment]
@vitorpamplona , can you build for iOS yet?  If not, @davidbiga thinks it is working.  Can you two confirm?

**Comment by vitorpamplona** [comment]
There seems to be something wrong with the xCode config files. It still thinks the app is inside a folder called tripleblind.

**Comment by yasushisakai** [comment]
I also confirm develop branch b77bf1c80e7e7598f97d751388ff9a2d187b92f6 builds in iPhoneSE

**Comment by penrods** [comment]
Boom, done!
