### ISSUE TITLE
Layout broken

### ISSUE THREAD

**Issue by vitorpamplona** [tripleblindmarket/private-kit#185]
We need to be more conscious of the different screen sizes. Should we move Import/Export buttons to Menu/Settings? 

![image (1)](https://user-images.githubusercontent.com/532031/77455363-21728580-6dd0-11ea-9c38-74388b181115.png)

**Comment by StartupSam** [comment]
Getting an even worse break on my older Android phone (OnePlus 3):

![screenshotAndroid](https://user-images.githubusercontent.com/6233577/77473521-9bf8d080-6de3-11ea-8b0e-2bfd54798e2e.jpg)

**Comment by StartupSam** [comment]
Can someone mark this as urgent? A number of core functions are unreadable as it is

**Comment by E3V3A** [comment]
@rparet  Please add to the back log.

**Comment by penrods** [comment]
The immediate need has been addressed with the nightly buiild.  A larger UI overhaul will be happening in the near future as more things get crammed on the main screen.
