### ISSUE TITLE
Android App Crashes - Due to Bluetooth

### ISSUE THREAD

**Issue by harshvitra** [tripleblindmarket/private-kit#207]
**Reproduce with these steps -** 

Click on Start logging and this issue crashes the app. Sometimes it shows the error below, sometimes it just freezes. 

The console reads - Starting Bluetooth, but neither it started nor it asked for any permissions (2nd Image)

<img height="427" alt="Screenshot 2020-03-26 at 5 17 22 AM" src="https://user-images.githubusercontent.com/25605193/77596029-dc119d80-6f20-11ea-8fd7-9fe4933176b6.jpg">

<img width="427" alt="Screenshot 2020-03-26 at 5 17 22 AM" src="https://user-images.githubusercontent.com/25605193/77596110-111df000-6f21-11ea-870c-807a02eb2387.png">

**Comment by tremblerz** [comment]
Can you check your version of `react-native-ble-advertiser` ? It should be 0.0.4
We were trying to fix this issue specifically and having this version solved the problem.

**Comment by harshvitra** [comment]
> Can you check your version of `react-native-ble-advertiser` ? It should be 0.0.4

Yes it is 0.0.4

**Comment by E3V3A** [comment]
I thought someone pushed some BT fixes a few days ago... 
Is this still an issue?

**Comment by harshvitra** [comment]
Yes this issue can be closed
Tested in the latest build
