### ISSUE TITLE
Add APK to releases

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/private-kit#209]
Please add also the APK's to the releases.

**Comment by E3V3A** [comment]
Or at least post the debug versions somewhere so that i can help debug the app before it's outdated by new releases. Thanks.

**Comment by rparet** [comment]
You can sign up for Google Play internals channel. Details in Slack.

**Comment by E3V3A** [comment]
@rparet 
Can you send me an invite to slack? For some reason I could not access it...
