### ISSUE TITLE
AOS v0.5.8 freezes and force closes after restart

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/private-kit#220]
teasting on AOS 6.0 
* App immediately crashes after installing v0.5.8 over older version
* clearing cache/data, app starts but freeze after selecting logging
* force closing app, and then restarting make app immediately force close at each startup.

Sorry guys, this app is simply not fit for release!  (At least v0.5.4 seem to work.)

**Comment by rparet** [comment]
Could you elaborate on AOS 6.0? Android version, device version?

**Comment by E3V3A** [comment]
Android 6.0 Marshmallow (API 23) , Huawei w. EMUI 4.1

**Comment by rparet** [comment]
So this app is only built for Android 9 and above.

**Comment by E3V3A** [comment]
> So this app is only built for Android 9 and above.

Well, that's not true.
https://github.com/tripleblindmarket/private-kit/blob/develop/android/build.gradle#L8

 (Besides v0.5.10 works.)
