### ISSUE TITLE
iOS: Exporting multiple times within few minutes gap shows wrong Log data

### ISSUE THREAD

**Issue by skusunam** [tripleblindmarket/private-kit#230]
I tried exporting data multiple times within a few minutes gap and every time it jumped  30-45-60mins instead of actual minutes.

9:28 PM  -  Log has data of 7 hours and 55 minutes 
9:31 PM  -  Log has data of 8 hours and 55 minutes
9:34 PM  -  Log has data of 10 hours and 0 minutes
9:36 PM  -  Log has data of 10 hours and 45 minutes
9:38 PM  -  Log has data of 11 hours and 25 minutes

<img src="https://user-images.githubusercontent.com/352861/77717551-c8147d00-6fae-11ea-8f89-7caa3e7bab9e.png" width="30%">
<img src="https://user-images.githubusercontent.com/352861/77717550-c77be680-6fae-11ea-88b5-79c173650fc1.png" width="30%">
<img src="https://user-images.githubusercontent.com/352861/77717548-c6e35000-6fae-11ea-80c6-3f4855d1b491.png" width="30%">
<img src="https://user-images.githubusercontent.com/352861/77717545-c64ab980-6fae-11ea-84ca-8e75cd5448f9.png" width="30%">
<img src="https://user-images.githubusercontent.com/352861/77717539-c3e85f80-6fae-11ea-8b72-9fd7ae7140e7.png" width="30%">

**Comment by thetimbanks** [comment]
I think this is due to how it calculates the time. It doesn't actually use the timestamp from the logging data. I just takes the point count and multiply it by 5 (since it logs every 5 minutes). I have started working on an update to this. I will spend some more time on it today.

**Comment by skusunam** [comment]
@thetimbanks awesome. Thank you. Let me know if you need another set of eyes to validate anything.

**Comment by tremblerz** [comment]
@thetimbanks has pointed it out correctly, in addition, it is also linked with how location is being recorded using the callback function, would be great if someone can evaluate this part as well, my initial experiments suggest that it has got to do with the speed of the device, at least on iOS.
