### ISSUE TITLE
How do I mark myself as infected or healthy?

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/private-kit#260]
Please explain how the app is helping me to see if I have been in contact with anyone infected. 

Since there is no way to mark yourself as _healthy_ or _infected_ within the app, I suppose it must be using **dark magic** to accomplish this feature? 

Please explain this somewhere! 

PS. I am about to share the app info to all my friends, but I doubt they will use it, unless they understand how this works and how it can benefit them.

**Comment by pmkees** [comment]
Hi- 
Just a  user here, but figured I'd respond.

There's no self-reporting capability. 
It is still early days for the project and very much a work-in-progress. 

From the  "Latest News" page in the app (2020-03-28) more functionality is on its way and the practical value for using it now is to start building your path data now so you'll be able to use it as features and capabilities become available in the future.

I'm using v0.5.10 (via Google Play) and it has a rudimentary overlap view comparing your personal path with data from a [public dataset](https://github.com/beoutbreakprepared/nCoV2019). The current utility value of the overlap view is low but I'm pretty sure this is only the start for future capabilities.

Check out the white paper (or the convenient summary) for the bigger picture thinking and where the app fits in at:
[privatekit.mit.edu](https://privatekit.mit.edu)

-pk

**Comment by E3V3A** [comment]
Hi @pmkees !

Thanks for taking the time to respond. So yep, that clarifies a lot. I tried to get the idea from the white paper, but then I didn't see it in the app and the README doesn't mention it it either. I requested at east that to be added in another issue #203, but was brushed off to _look at the website_. As a developer myself, I'm sick of looking at outdated websites for simple instructions that is meant to be present in a README, or better, in the app itself.

**Comment by E3V3A** [comment]
> It is still early days for the project and very much a work-in-progress.

Can someone please provide an ETA? 
- We obviously don't have several weeks. f we wait more than 1 month, we can be pretty sure this app will become fairly useless. (My educated but opinionated guess.)

**Comment by penrods** [comment]
This weekend we have a bunch of people who have joined who don't have to keep their heads down in code.  More information at both the high and low levels will be available in the next few days.

Short answer to the original question:  We don't believe self-reporting is a good idea for a few reasons, so our initial plan is to rely on Health Authorities to validate and contact trace.  That step relies on this app, but the actual tracing is done using toolsets in https://github.com/tripleblindmarket/safe-places

Thanks for the support!  Tell all your friends!

**Comment by E3V3A** [comment]
@penrods @pmkees 
> We don't believe self-reporting is a good idea

Huh? That doesn't make any sense. Why not? Who else would report you?

> our initial plan is to rely on Health Authorities to validate and contact trace

Woot? Sorry, but this is simply not realistic. We're in the middle of a war and you expect the *Health Authorities* to waste their time and resources to validate and manually report test results. I can promise you *that* is simply not going to happen! :disappointed: 

The other reason it's not going to happen is that you'd need to convince and coordinate data feed from all those "authorities" in the entire worlds 195 countries. Good luck with that! (I've tried to get data feed from the tiny little country I'm in, but that is a huge obstacle here as the gov't just isn't willing to cooperate with anyone outside their own office and doesn't even know how, if they wanted.) 

Unfortunately we're on our own on this, so I really hope you guy's would reconsider those decisions.

**Comment by penrods** [comment]
This actually is happening.  I have been on the phone with authorities in 7 different countries today and will be piloting the first starting tomorrow.  Not to mention the dozens of individual cities I and many others in our group have spoken with.  This _is_ crazy, but it also is happening!
