### ISSUE TITLE
Development environment setup: improve docs

### ISSUE THREAD

**Issue by darioscarpa** [tripleblindmarket/private-kit#267]
I'm sure that there are many developers willing to help on this project but that, like myself, usually operate with totally different technologies (in my case: videogames/XR development).
I think a couple notes in README.md and dev_setup.sh could save time to these devs, mainly:

- Clarifying that you can get a working development environment on Windows too, if needed. A dev_setup.bat could be added to do some of the work and guide through the manual steps, but a dev_setup_win.txt with some notes/links could suffice.

- Reminding that you have to setup a Google Maps API key to get a working build. My first build in the emulator faced me with a blank map, and I noticed that happening to a fellow dev on Slack too.

If you agree that this is worthwile, I'll prepare a PR suggesting these changes, based on my setup experience.

**Comment by E3V3A** [comment]
I was asking a similar thing in #203 ... 
I would love to see this as well. So perhaps do a PR, but put it in a separate `*.md`, maybe.

**Comment by rparet** [comment]
I agree that it's worthwhile. Please submit a PR!

**Comment by thetimbanks** [comment]
Added the setup instructions for the Google API key in https://github.com/tripleblindmarket/private-kit/pull/277

**Comment by darioscarpa** [comment]
Awesome, meanwhile I started working on the Windows setup script. Hopefully I'll be done before tomorrow evening.

**Comment by E3V3A** [comment]
@darioscarpa 
> the Windows setup script

Are you going to use *Powershell*, or something else?

**Comment by darioscarpa** [comment]
@E3V3A a .bat file, also opening a Powershell to install Chocolatey (which helped a lot in automating part of the process).

**Comment by E3V3A** [comment]
@darioscarpa 
Can you document what need to be installed using Chocolatey? 
It's should be easily found either in an *readme.md or in the Wiki.
