### ISSUE TITLE
Is this app meant for global use or only US?

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/private-kit#270]
After having my previous issue #260 closed, I am quite concerned about the decision that the app will not allow people to self report, but one is expected to have the "local health authorizes" do that for you. 
(See my [comment on that](https://github.com/tripleblindmarket/private-kit/issues/260#issuecomment-605644802). - I's not gonna happen.) 

So the main question, which could be deal breaker for me, is:

**Will this app be a globally supported project or only possible to use in some specific region?**

**Comment by rparet** [comment]
Global use! Please see the documentation available on Slack or via the Safepaths web site!
