### ISSUE TITLE
syntax error, missing comma in languages.js (fixed)

### ISSUE THREAD

**Issue by alpita-masurkar** [tripleblindmarket/private-kit#323]
Missing comma in the block of code below in languages.js. Fixed, please merge this soon
gj: {
       translation: {
         label: gjlabels,
       }
     },

**Comment by alpita-masurkar** [comment]
this is fixed in #318 please merge

**Comment by harshvitra** [comment]
@rparet  

Fixed in #318 and merged, we can close this one
