### ISSUE TITLE
View overflows on small screen

### ISSUE THREAD

**Issue by tremblerz** [tripleblindmarket/private-kit#45]
The top part just goes away if the screen size is small.

**Comment by penrods** [comment]
Can you grab a screenshot?  What phone is this, resolution would be good to know if you can easily figure it out.

**Comment by bikramkhastgir** [comment]
I have seen the same issue. Mine is Moto-G4 Plus. 

![WhatsApp Image 2020-03-15 at 1 35 51 PM](https://user-images.githubusercontent.com/7278304/76697830-1168f080-66c2-11ea-90fc-9fd629d0f47a.jpeg)

**Comment by harshvitra** [comment]
This can be closed @penrods , fixed in #81

**Comment by rparet** [comment]
Closed.
