### ISSUE TITLE
Android: App Crash

### ISSUE THREAD

**Issue by bikramkhastgir** [tripleblindmarket/private-kit#47]
App Crashes when Denied permission for "location" access permission when started app for the first time.

**Comment by penrods** [comment]
Let's retry this after #64

**Comment by rparet** [comment]
@bikramkhastgir can you verify that this is fixed for you on the latest version in the Play Store?

**Comment by bikramkhastgir** [comment]
@rparet , The crash issue is solved. Thank you.
But even if i am not giving permission to access my location, the app screen still changes to show "Stop Logging". I guess it should be in the "Start Logging" page until it gets the permission.

Also if someone changes the permission in settings manually, then also the app page should stay at "Start Logging" with option to access the settings page to give location permission.

**Comment by rparet** [comment]
@bikramkhastgir I see that - looks like there's a specific bug for this: #129, so closing this one and will follow up there. Thank you!
