### ISSUE TITLE
Debugger warnings when loading app (require cycles)

### ISSUE THREAD

**Issue by andreanuzzo** [tripleblindmarket/private-kit#54]
I am getting a lot of these warnings when opening the app. 
Xcode 10.2 and iOS 13.3.2 simulator (iPhone 8).

![image](https://user-images.githubusercontent.com/36167533/76712058-99172500-66eb-11ea-9468-452848d20560.png)

I'm not an iOS developer, but I can try to fix it if needed.

**Comment by penrods** [comment]
I see this under Android too.  If you can investigate, please do.  I don't think this is dangerous, so I've been ignoring it.  But it would be nice to eliminate if possible.

**Comment by andreanuzzo** [comment]
It is related to a known bug of rn-fetch-blob, left unfixed for a couple of years. 

https://github.com/joltup/rn-fetch-blob/issues/183#issuecomment-450826541

I have fixed it manually with MIT's `patch-package`.
