### ISSUE TITLE
Prettier throws warnings for incorrect formatting

### ISSUE THREAD

**Issue by tushar-dadlani** [tripleblindmarket/private-kit#62]

**Comment by penrods** [comment]
What do you think about doing something like this:
https://www.reactnative.guide/6-conventions-and-code-style/6.2-git-pre-hooks.html

Package.json requirements that installs Husky that uses git precommit hooks to enforce standards?

The examples on that page aren't prettier, but should be possible with that approach.

**Comment by tushar-dadlani** [comment]
That makes sense. We could also add a helper command to package.json

**Comment by rparet** [comment]
@StartupSam is working on this now.

**Comment by tushar-dadlani** [comment]
Prettier 2.0 was recently announced, just wanted to throw it out there. https://prettier.io/blog/2020/03/21/2.0.0.html

**Comment by StartupSam** [comment]
Lol, literally announced the day I made the change - will take a look, but am focused on design work at the moment. If there's anything you see in 2.0 that's a must-have, feel free to upgrade it @tushar-dadlani
