### ISSUE TITLE
Stop recording location does not remove the notification bar

### ISSUE THREAD

**Issue by tremblerz** [tripleblindmarket/private-kit#66]
When the location logging is not on, even then the notification bar keeps showing the location is getting recorded.

**Comment by chasejjw** [comment]
Do you mean the system's notification icon remains on? Can you provide a screenshot?

**Comment by tremblerz** [comment]
Yes, so if I press stop logging location then exit the App. I am still shown that the notification is getting logged. And this notification doesn't get removed.
