### ISSUE TITLE
Refine Share

### ISSUE THREAD

**Issue by penrods** [tripleblindmarket/private-kit#68]
The basic Share functionality works, but it could use some refinement.  Specfically two things:

* Improve the filename.  Currently it is "<number>.null".  Change it to be "PrivateKit_<number>.json"
* Add a message body.  Try:
  `Here is my location log from Private Kit.`
* If titles are supported, make it: "Shared PrivateKit_<number>.json"

**Comment by tushar-dadlani** [comment]
`.null` is on android on iOS it shows up as `(null)-someid.data`

improved the filename for android, need someone to test, for iOS - will need to do something like https://github.com/react-native-community/react-native-share#share-remote-pdf-file-with-gmail--whatsapp-ios

I have made some changes here: https://github.com/tushar-dadlani/private-kit/tree/tdadlani/fix_share_name

would love your thoughts before I open a PR

**Comment by tremblerz** [comment]
Looks good based on changes, haven't tested it yet. Can you open a PR @tushar-dadlani ?

**Comment by tushar-dadlani** [comment]
I am breaking this into 2 parts 
1. Save file to disk with the correct name
1. Share the file from filesystem
1. delete the file locally

**Comment by tremblerz** [comment]
I would recommend avoiding that route if possible because other Apps can pickup for the time it is on disk (making the data non-private in a sense). At the same time I am aware of this issue being the library issue not ours so take your call.

**Comment by tremblerz** [comment]
Export on iOS is still an issue when sent as an attachment on Apps like gmail and whatsapp

**Comment by tremblerz** [comment]
Fixed in #283
