### ISSUE TITLE
Improve the saved point description

### ISSUE THREAD

**Issue by penrods** [tripleblindmarket/private-kit#71]
Currently the Export page shows some basic info about the saved data.  It displays:
   ```Points to be shared:  6134```

We should expand this into something more friendly.  Describe number of points, oldest date, and how recently it was updated.

Example:  
```
Log has 22 days, 345 points, last updated 4 minutes ago.
```

Once that is possible, we can see it if will fit on the main screen, updated each time a new point is saved.

NOTE: Be aware that the stored datetime info is in UTC.  Should be able to just subtract the first point's time from the current unixtimeUTC, then do division to figure out the number of days saved.

**Comment by meahmed** [comment]
I would like to work on this issue. Can you assign this to me?

**Comment by penrods** [comment]
I know there will be overlaps, but at this time we aren't assigning issues to just one person.  Go ahead and start on it and submit a PR.  We might end up with some duplicates, but this also won't deter others from looking at things in different ways.

**Comment by penrods** [comment]
In your PR, reference this issue by #71.  It will automatically associate on Github.

**Comment by harshvitra** [comment]
We have partially fixed this in #81 

We just have to work on this part - last updated 4 minutes ago.
