### ISSUE TITLE
Audit licenses

### ISSUE THREAD

**Issue by penrods** [tripleblindmarket/private-kit#75]
We need to audit the licenses of all plugins in.  Note any that require a visible attribution.  If we have any, we will need to create an About page that shows that.

**Comment by hichrislife** [comment]
Currently, there's no license issue. 

Just some risks...
minimist@0.0.8
mem@1.1.0
yargs-parser@11.1.1

**Comment by rparet** [comment]
Thanks Chris! I also attached the doc you sent here.
[risk_03192020.pdf](https://github.com/tripleblindmarket/private-kit/files/4355416/risk_03192020.pdf)
