### ISSUE TITLE
Redirect to settings in iOS for always on location settings

### ISSUE THREAD

**Issue by tremblerz** [tripleblindmarket/private-kit#79]
In iOS, we haven't found a way so far to have always on location settings enabled through pop-up which comes on the app. So for now, we will redirect the user to location settings where they can click on always on.

**Comment by tremblerz** [comment]
@1geek0 and I are dealing it with for now

**Comment by snmishra** [comment]
I'm willing to take a stab at it. If someone with more experience with location stuff wants to jump in, feel free. 

Looks like we need another library to do this well. Will another dependency be acceptable?

[react-native-geolocation-service](https://github.com/Agontuk/react-native-geolocation-service) is free

[react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation) looks more advanced, but needs a license. I could ask the author if they're willing to give a discounted or free license for this.

**Comment by skusunam** [comment]
@tremblerz not sure if you already read this. From iOS-13 it will not show the "Always" option when the first time it asks i.e. it will show 3 options:
1. Allow While Using App
2. Allow Once
3. Don't Allow

If the user grants you ‘Allow While Using App’ permission and if you try to scan for location in the background, only then the user will be presented a 2nd dialog to grant the background permission i.e. new popup with following 2 options:
1. Keep Only While Using
2. Change to Always Allow

I will give a try with this App and make sure it shows-up 2nd popup. 

Let me know if you have any questions for me? Feel free to assign this issue and any related issues to me?

**Comment by rparet** [comment]
fix is in #216

**Comment by tremblerz** [comment]
Done in #97
