### ISSUE TITLE
Play Store says App incompatible with all your devices[One Plus 5T, Android 8.1.0]

### ISSUE THREAD

**Issue by nehalsep7** [tripleblindmarket/private-kit#85]
<img width="727" alt="Screenshot 2020-03-18 at 1 29 20 AM" src="https://user-images.githubusercontent.com/4056359/76896492-e811b580-68b7-11ea-8989-cfc776ad7f7e.png">

**Comment by douglara** [comment]
Im have same issue, my device is Galaxy S9 (SM-G9600) from brasil play store.

**Comment by douglara** [comment]
The last update fixed it for me =)
@nehalsep7 try by link: https://play.google.com/store/apps/details?id=edu.mit.privatekit

**Comment by nehalsep7** [comment]
Yes, works now, closing this issue
