### ISSUE TITLE
Feature - Localize the app to support various languages

### ISSUE THREAD

**Issue by harshvitra** [tripleblindmarket/private-kit#87]
**What is the feature -** 

Setup Internationalization framework to make the app multilingual.

**What this feature can do -** 

1. detect the user language
2. load the translations
3. optionally cache the translations
4. etc

**Why is it needed -**

When the app will reach millions of people around the globe, they will prefer to have it in their local language.

**Comment by andreanuzzo** [comment]
Can help with Italian (native speaker), French and German

**Comment by douglara** [comment]
I can help with português Brasil

**Comment by harshvitra** [comment]
@andreanuzzo @douglara 

Once this PR is merged we can start contributing to various languages - https://github.com/tripleblindmarket/private-kit/pull/119/

Each language has a different folder and has various json files. 

All you need to do is refer the folder name here - https://developer.chrome.com/webstore/i18n
In that folder edit the json files and replace the english content to whichever language you've selected. 

**Note: Don't change the keys only the values**

**Comment by tremblerz** [comment]
PR is merged, you guys can start adding now

**Comment by penrods** [comment]
I'm closing this general one (thanks, @harshvitra !)

Let's have independent issues for each language so we can check them off.
