### ISSUE TITLE
Apple Rejection: Do we need Motion Tracking? 

### ISSUE THREAD

**Issue by vitorpamplona** [tripleblindmarket/private-kit#89]
We noticed that your app requests the user’s consent to access their motion but does not clarify the use of the motion in the applicable purpose string.

Next Steps

Please revise the relevant purpose string in your app’s Info.plist file to specify why the app is requesting access to the user's motion and location. You can modify your app's Info.plist file using the property list editor in Xcode.

To help users understand why your app is requesting access to their personal data, all permission request alerts in your app should specify how your app will use the requested feature.

**Comment by penrods** [comment]
The BackgroundGeolocation uses it to determine when to hit the GPS.  If the phone isn't moving it (by accelerometers) it doesn't read the GPS.  This is for battery purposes.  That seems legit to me, to be honest.

**Comment by tremblerz** [comment]
I think it brings doubt to people though on why it needs motion tracking

**Comment by penrods** [comment]
More intro text can help with this -- that is the value of the Welcome screen sequence.

**Comment by vitorpamplona** [comment]
Also, Apple will keep rejecting us until we are VERY clear on the description of the app why we need these permissions.
