### ISSUE TITLE
Onboarding Screen for location permission is flickering on iOS 

### ISSUE THREAD

**Issue by sparks2209** [tripleblindmarket/private-kit#890]
Issue with latest develop branch, after cloning branch Onboarding screen which is asking for location and notification permission getting flicker after allowing notification 

Tested on iPhone 5s simulator, iOS 11.2

## Steps to reproduce
Launch the app and go to Onboarding screen for permission screen, UI is flickering after allwoing notification popup.
![Simulator Screen Shot - iPhone 5s - 2020-05-22 at 14 43 25](https://user-images.githubusercontent.com/46887319/82657375-e1e6df00-9c42-11ea-9a7f-cace3cb90dca.png)
<img width="1680" alt="Screenshot 2020-05-22 at 3 57 32 PM" src="https://user-images.githubusercontent.com/46887319/82658817-4e62dd80-9c45-11ea-918f-2a9e85a12f73.png">

**Comment by sparks2209** [comment]
@summetj whom i can reach out for this issue, latest changes in Onboarding file caused this issue.

**Comment by johnschoeman** [comment]
Thanks for creating an issue! We've been updating this screen for the bluetooth release and have also noticed the bug that was introduced. so we are probably in a good position to address it.  cc: @tparesi , @mattThousand

**Comment by sparks2209** [comment]
Thank you , two small observations Location and  Bluetooth permissions assigned with nextStep instead of PermissionStatus
 setLocationPermission(nextStep); --- 151
 setBluetoothPermission(nextStep); -- line number 186

**Comment by johnschoeman** [comment]
resolved in: https://github.com/Path-Check/covid-safe-paths/pull/891, cc: @sparks2209
