### ISSUE TITLE
Enabling location permission is missing during Onboard and Setting screen.

### ISSUE THREAD

**Issue by sparks2209** [tripleblindmarket/private-kit#911]
From latest upstream develop changes, screen for permissions is not appearing during on board.

![Simulator Screen Shot - iPhone 11 - 2020-05-26 at 11 19 22](https://user-images.githubusercontent.com/46887319/82864880-2de79b80-9f43-11ea-9e91-ea20f3418914.png)
![Simulator Screen Shot - iPhone 11 - 2020-05-26 at 11 19 39](https://user-images.githubusercontent.com/46887319/82864887-317b2280-9f43-11ea-9ee3-3f5635d1a542.png)
![Simulator Screen Shot - iPhone 11 - 2020-05-26 at 11 21 44](https://user-images.githubusercontent.com/46887319/82864890-3213b900-9f43-11ea-8c37-334dac17f6af.png)
![Simulator Screen Shot - iPhone 11 - 2020-05-26 at 11 21 48](https://user-images.githubusercontent.com/46887319/82864895-3344e600-9f43-11ea-8309-ff7559a1eb83.png)

Enable contact tracing on Dashboard not working, it's taking to settings screen of app but option to enable Location is missing from the list.

Tested on iPhone 11 - iOS 13.2.2

**Comment by Patrick-Erichsen** [comment]
@sparks2209 It looks like you built the Bluetooth version of the app - this is a relatively recent implementation. 

Can you comment on what command you used to build the app?

In the meantime, try `yarn run-android-gps` or `yarn run-ios-gps` to build the GPS app.

**Comment by sparks2209** [comment]
i used react-native run-android and react-native run-ios 
yarn run-android-gps or yarn run-ios-gps helped me build app.
