### ISSUE TITLE
Clicking on privatekit link during welcome screen throws error

### ISSUE THREAD

**Issue by tremblerz** [tripleblindmarket/private-kit#92]
My guess is it just needs to load one library responsible for this. Didn't look into detail, this got popped up while fixing some other issue.
<img width="403" alt="Screen Shot 2020-03-18 at 7 41 40 PM" src="https://user-images.githubusercontent.com/10557215/77017333-a08b3800-6950-11ea-9ae4-ad851447d4df.png">

**Comment by nehalsep7** [comment]
working on this
