### ISSUE TITLE
Android location permission showing denied intially

### ISSUE THREAD

**Issue by Namit-Agrawal** [tripleblindmarket/private-kit#942]
## Steps to reproduce
Download the app
Navigate through the permission steps in onboarding
Location access will show up as denied (Red checkmark) before  user can approve/deny location permissions

## Expected Behavior
Location access should be unchecked initially, i.e not denied or granted.

![per](https://user-images.githubusercontent.com/43054656/83539346-862b1a00-a4bc-11ea-8b44-46b469a76bd1.jpg)

**Comment by crayne** [comment]
I can work on this if no one else is and it is not obsolete.  Is this the GPS or BT version?  Which device or emulator?  Thanks.

**Comment by summetj** [comment]
@crayne - This is for the GPS version (BT / Aurora can not use location data), but given the age it may very well be obsolete. You'd have to run a development version of the app and see if the bug still occurs or not. Let me know if we should mark it resolved.

**Comment by crayne** [comment]
This does not still occur and can be marked resolved.  However, if you say you want to skip enabling location, there is another problem for which I will make a separate issue.
